# gradle.properties
MYAPP_UPLOAD_STORE_FILE=lifeLogKey
MYAPP_UPLOAD_KEY_ALIAS=lifeLog
MYAPP_UPLOAD_STORE_PASSWORD=rmtm1234!@
MYAPP_UPLOAD_KEY_PASSWORD=rmtm1234!@

# Gradle Memory Settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Temporary bypass for Hilt compatibility with AGP 9.0+
android.builtInKotlin=false
android.newDsl=false
ksp.useKSP2=false
